spring:
 application: 
  name: customer-service
  
server:
  port: 8092
  
account-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8091
  
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/
   
